name: Android Build & Video Encode

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Convert PNG frames to MP4 video
        run: |
          cd app/src/main/assets/frames  # Change this path if your frames folder is different
          ffmpeg -framerate 10 -i frame_%03d.png -c:v libx264 -pix_fmt yuv420p output.mp4

`
