name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Clear Gradle Cache
        run: rm -rf ~/.gradle/caches/
      - name: Grant execute permission for gradlew
        run: |
          if [ -f gradlew ]; then
            chmod +x gradlew
          else
            echo "gradlew file not found, please ensure it is committed to the repository"
            exit 1
          fi
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run unit tests
        run: ./gradlew test
