name: Update Gradle Wrapper
on: workflow_dispatch
jobs:
  wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run wrapper
        run: ./gradlew wrapper --gradle-version 8.0
      - name: Commit wrapper files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gradle/wrapper/gradle-wrapper.jar
          git add gradle/wrapper/gradle-wrapper.properties
          git commit -m "chore: update gradle wrapper to 8.0"
          git push
